apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-container
          image: your_image_from_container_registry
          imagePullPolicy: Never
          ports:
            - containerPort: port_of_your_choice
          env:
            - name: var_name
              value: "some_value"
